defaults:
  - base_dataset
name: coco_on_places
batch_size: 64
num_classes: 9
data_dir: ${paths.root}/datasets/${dataset.name}
normalize: false
augmentations:
  RandomCrop:
    enabled: True
    size: 64
    padding: 8
    padding_mode: 'reflect'
  RandomHorizontalFlip:
    enabled: True
    p: 0.5

original_image_size: 178
image_size: 64
test_augmentations:
  Dummy:
    enabled: False