defaults:
  - base_optimizer
name: SGD
args:
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9
  nesterov: True

lr_warmup:
  epochs: 5
  start_lr: 1e-2
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [100, 120, 140]
    gamma: 0.1
epochs: 150
