defaults:
  - base_optimizer
name: SGD
args:
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9
lr_warmup_epochs: 5
lr_warmup_start_factor: 0.001
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [50, 70, 80]
    gamma: 0.1
epochs: 90
