defaults:
  - base_optimizer
name: SGD
args:
  lr: 0.1
  weight_decay: 5e-4
  momentum: 0.9
lr_scheduler:
  type: MultiStepLR
  args:
    milestones: [50, 70, 80]
    gamma: 0.1
lr_warmup:
  epochs: 5
  start_lr: 1e-3
epochs: 90